name: denner-public-api-spec

proxy:
  appserver:
    - denner-public-api-spec.detailnet.me

env_file:
  - .lando.env

services:
  appserver:
    type: apache
    webroot: docs
    build_as_root:
      - ./docker/install-utilities.sh
      - ./docker/install-java-environment.sh # Could use a separated service for JRE (would be faster)
      - ./docker/install-aws-cli.sh
    run:
      - . ./docker/download-swagger-codegen.sh
tooling:
  build-docs:
    description: Update openapi definition for docs from the swagger source
    service: appserver
    cmd: java -Dfile.encoding=UTF-8 -jar docs/.swagger-codegen/swagger-codegen-cli.jar generate -i src/swagger.yml -l openapi -o docs
  export-api:
    description: Download API Gateway definition from production stage (to be committed in this project for VCS)
    service: appserver
    cmd: aws apigateway get-export --parameters extensions='apigateway' --export-type oas30 --accept application/yaml --rest-api-id 7xu6cbcuej --stage-name prod src/denner-public-prod-oas30-apigateway.yaml
