x-detail-stage-variables:
  prod:
    - lambda_env: "prod"
    - lambda_alias: "live"
    - articles_url: "denner-art-new.frb.io/api"
    - articles_app_id: "XXX"
    - articles_app_key: "XXX"
    - advertising_url: "denner-adv-new.frb.io/api"
    - advertising_app_id: "XXX"
    - advertising_app_key: "XXX"
    - stores_url: "denner-sts-new.frb.io/api"
    - stores_app_id: "XXX"
    - stores_app_key: "XXX"
    - mobile_api: "denner-mobile-api"
  test:
    - lambda_env: "test"
    - lambda_alias: "live"
    - articles_url: "denner-articles-test.detailnet.ch/api"
    - articles_app_id: "XXX"
    - articles_app_key: "XXX"
    - advertising_url: "denner-advertising-test.detailnet.ch/api"
    - advertising_app_id: "XXX"
    - advertising_app_key: "XXX"
    - stores_url: "denner-stores-test.detailnet.ch/api"
    - stores_app_id: "XXX"
    - stores_app_key: "XXX"
    - mobile_api: "denner-mobile-app"
x-detail-api-gatway-permissions:
  prod: >
    aws lambda add-permission --action lambda:InvokeFunction --function-name "arn:aws:lambda:eu-west-1:802555642192:function:denner-lambda-tools-prod_createBasePoster:live"         --source-arn "arn:aws:execute-api:eu-west-1:802555642192:7xu6cbcuej/*/POST/base-posters"    --principal apigateway.amazonaws.com --statement-id 76276df8-024c-42bb-8eb6-c8d47e8c3b34
    aws lambda add-permission --action lambda:InvokeFunction --function-name "arn:aws:lambda:eu-west-1:802555642192:function:denner-mobile-api-prod_listOnlineArticlesForGroup:live" --source-arn "arn:aws:execute-api:eu-west-1:802555642192:7xu6cbcuej/*/GET/tobacco-articles" --principal apigateway.amazonaws.com --statement-id aeb71bfc-9ee7-497f-8907-bdaa82f0abd2
  test: >
    aws lambda add-permission --action lambda:InvokeFunction --function-name "arn:aws:lambda:eu-west-1:802555642192:function:denner-lambda-tools-test_createBasePoster:live"         --source-arn "arn:aws:execute-api:eu-west-1:802555642192:7xu6cbcuej/*/POST/base-posters"    --principal apigateway.amazonaws.com --statement-id 76276df8-024c-42bb-8eb6-c8d47e8c3b34
    aws lambda add-permission --action lambda:InvokeFunction --function-name "arn:aws:lambda:eu-west-1:802555642192:function:denner-mobile-app-test_listOnlineArticlesForGroup:live" --source-arn "arn:aws:execute-api:eu-west-1:802555642192:7xu6cbcuej/*/GET/tobacco-articles" --principal apigateway.amazonaws.com --statement-id aeb71bfc-9ee7-497f-8907-bdaa82f0abd2
  warning_note: >
    Denner Mobile Lambda function for test and prod are named differently: "denner-mobile-api-prod_..." vs. "denner-mobile-app-test_..."
